apiVersion: v1
kind: Service
metadata:
  name: sample-producer-svc
spec:
  selector:
    app: sample-producer
  ports:
    - port: 8098
      targetPort: 8098
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-producer
spec:
  selector:
    matchLabels:
      app: sample-producer
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 20%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-producer
    spec:
      containers:
        - name: sample-producer
          image: abdulfayis/sample-producer:latest
          ports:
            - name: sample-producer
              containerPort: 8098
          imagePullPolicy: Never    
